apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
   
resources:
- namespace.yaml                            # namespace je tiež zdrojom 
- ../../../infrastructure/ufe-controller       # kustomization pre ufe-controller
- ../../../infrastructure/fluxcd
- ../../../infrastructure/envoy-gateway
- ../../../infrastructure/cert-manager
- ../../../infrastructure/oauth2-proxy
- ../../../infrastructure/opa-plugin
- ../../../infrastructure/monitoring-opensearch
- ../../../infrastructure/fluentbit
- ../../../infrastructure/prometheus
- ../../../infrastructure/grafana
- ../../../infrastructure/jaegertracing
  
patches: 
- path: patches/ufe-controller.service.yaml    # úprava služby ufe-controller