apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
   
resources:
- namespace.yaml                            # namespace je tiež zdrojom 
- ../../../infrastructure/ufe-controller       # kustomization pre ufe-controller
- ../../../infrastructure/fluxcd
   
commonLabels:
  app.kubernetes.io/part-of: wac-hospital

   
patches: 
- path: patches/ufe-controller.service.yaml    # úprava služby ufe-controller