apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${templateOption:pfx}-cd  
  namespace: wac-hospital
spec:
  wait: true
  interval: 42s
  path: clusters/wac-aks
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${templateOption:pfx}-gitops-repo