apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
 - name: mongodb-connection
   literals:
    - host=mongodb
    - port=27017

secretGenerator:
  - name: mongodb-auth
    literals:
    - username=admin
    - password=admin

patches:
- path: patches/webapi.deployment.yaml
