apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${templateOption:pfx}-ambulance-webapi
spec:
  parentRefs:
    - name: wac-hospital-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - group: ""
          kind: Service
          name: ${templateOption:pfx}-ambulance-webapi
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /openapi
      backendRefs:
        - group: ""
          kind: Service
          name: ${templateOption:pfx}-openapi
          port: 80