apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: ${templateOption:dockerhubAccount}/ambulance-ufe
  newName: ${templateOption:dockerhubAccount}/ambulance-ufe 
  newTag: 1.0.0

replacements: 
  - targets:
    - select: 
        group: fe.milung.eu
        version: v1 
        kind: WebComponent
        name: ${templateOption:pfx}-ambulance-ufe 
      fieldPaths:
        - spec.hash-suffix
    source: 
      version: v1
      kind: Deployment
      name:  ${templateOption:pfx}-ambulance-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options: 
        delimiter: ':'
        index: 1