/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PfxAmbulanceWlList {
    }
}
declare global {
    interface HTMLPfxAmbulanceWlListElement extends Components.PfxAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPfxAmbulanceWlListElement: {
        prototype: HTMLPfxAmbulanceWlListElement;
        new (): HTMLPfxAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pfx-ambulance-wl-list": HTMLPfxAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface PfxAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pfx-ambulance-wl-list": PfxAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pfx-ambulance-wl-list": LocalJSX.PfxAmbulanceWlList & JSXBase.HTMLAttributes<HTMLPfxAmbulanceWlListElement>;
        }
    }
}
