name: Ambulance uFE CI
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v1*' 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [${templateOption:ciNodeVersion}]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
          # list of Docker images to use as base name for tags
          images: ${templateOption:dockerhubAccount}/ambulance-ufe
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}}
            type=ref,event=tag
            type=semver,pattern={{version}} # napr `1.0.0`
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}     
            type=raw,value=latest,enable={{is_default_branch}}
    - uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./build/docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }} 
        labels: ${{ steps.meta.outputs.labels }}
