kind: Service
apiVersion: v1
metadata:
  name: ${templateOption:pfx}-openapi-ui
spec:  
  selector:
    pod: ${templateOption:pfx}-ambulance-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80  
    targetPort: 8081