apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfx-ambulance-ufe-deployment      # meno deployment-u od ktorého sa odvádza meno podu @_pfx_@
spec:
  replicas: 2
  selector:
    matchLabels:
        pod: pfx-ambulance-ufe-label    # tento riadok je len označenie štítku  @_pfx_@
                                    # key-value pair pod=ambualnce ufe
                                    # určený pre výber podov s rovnakým štítkom
  template:                    # šablóna pre vytvorenie replík podov
    metadata:
      labels: 
        pod: pfx-ambulance-ufe-label    # štítky podu @_pfx_@
    spec:
      containers:
      - name: pfx-ambulance-ufe-container # meno kontaineru - v pod-e ich môže byť viac @_pfx_@
        image: pfx/ambulance-ufe #@_pfx_@
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:                  # určenie kvót pre využívané fyzické prostriedky
                                    # je dôležité pre riadenie záťaže v rámci kubernetes
                                    # klastra
            requests:               
                memory: "32M"
                cpu: "0.1"
            limits:
                memory: "320M"
                cpu: "0.3"