apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: ${templateOption:pfx}-ambulance-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: ${templateOption:pfx}-ambulance-webapi-config
    literals:
      - database=${templateOption:pfx}-ambulance
      - collection=ambulance
