name: Developer Containers Prebuilds

on:
  workflow_dispatch: {}

  pull_request:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

env: 
    IMAGE_NAME: milung/wac-devcontainer
    IMAGE_TAG: ${{ github.ref_name }}
    PLATFORM: linux/amd64,linux/arm64

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with: 
        use: true

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.0' 
      
    - name: Unify chapter templates
      shell: pwsh
      run: ./scripts/run.ps1 unify-templates

    - name: Install devcontainer
      run: npm install -g @devcontainers/cli 
    
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to registry 1
      uses: docker/login-action@v1
      with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Replace version in templates
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"${{ steps.get_version.outputs.VERSION }}\"/g" templates/**/devcontainer-template.json

    - name: Test all templates 
      shell: pwsh
      run: ./scripts/run.ps1 test

    - name: Publish Templates
      continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/v')
      run: devcontainer templates publish -r registry-1.docker.io -n milung ./templates

    - name: Pre-Build Dev Container
      run: devcontainer build --workspace-folder ./prebuild --platform $PLATFORM --image-name $IMAGE_NAME:$IMAGE_TAG  --push

