name: Developer Containers Prebuilds

on:
  workflow_dispatch: {}

  pull_request:
  push:
    branches: [ "step-*" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:        
        imageName: milung/wac-devc-ufe
        imageTag: ${{ github.ref_name }}
        platform: linux/amd64,linux/arm64
    