name: Developer Containers Prebuilds

on:
  workflow_dispatch: {}

  pull_request:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

env: 
    IMAGE_NAME: milung/wac-devcontainer
    IMAGE_TAG: ${{ github.ref_name }}
    PLATFORM: linux/amd64,linux/arm64

jobs:
  find-tests:
    name: Find Test
    runs-on: ubuntu-latest
    container: debian:buster-slim
    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v1

      - id: tests
        uses: philips-labs/list-folder-action@v1
        with:
          path: ./tests

  test-templates:
    name: Test Template
    needs: find-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.find-tests.outputs.folders) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0' 

      - name: Test template ${{ matrix.folder }} 
        shell: pwsh
        run: ./scripts/run.ps1 test ${{ matrix.folder }}

  build:
    runs-on: ubuntu-latest
    name: Build and publish dev container and templates
    needs: test-templates
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with: 
        use: true
      
    - name: Unify chapter templates
      shell: pwsh
      run: ./scripts/run.ps1 unify-templates

    - name: Install devcontainer
      run: npm install -g @devcontainers/cli 
    
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to registry 1
      uses: docker/login-action@v1
      with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Replace version in templates
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"${{ steps.get_version.outputs.VERSION }}\"/g" templates/**/devcontainer-template.json

    - name: Publish Templates
      continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/v')
      run: devcontainer templates publish -r registry-1.docker.io -n milung ./templates

    - name: Pre-Build Dev Container
      run: devcontainer build --workspace-folder ./prebuild --platform $PLATFORM --image-name $IMAGE_NAME:$IMAGE_TAG  --push

