apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${templateOption:pfx}-install
  namespace: wac-hospital
spec:
  wait: true
  dependsOn: 
  - name:  prepare
  interval: 42s
  path: clusters/localhost/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${templateOption:pfx}-gitops-repo